repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: local
    hooks:
      - id: flutter-analyze
        name: Flutter Analyze
        entry: bash -c 'cd dogdog_trivia_game && flutter analyze'
        language: system
        types: [dart]
        pass_filenames: false

      - id: flutter-format
        name: Flutter Format
        entry: bash -c 'cd dogdog_trivia_game && dart format --set-exit-if-changed .'
        language: system
        types: [dart]
        pass_filenames: false

      - id: flutter-test
        name: Flutter Test
        entry: bash -c 'cd dogdog_trivia_game && flutter test'
        language: system
        types: [dart]
        pass_filenames: false
